[deploy]
bucket = 'cfn-artifacts-mocharoll'
region = 'us-west-2'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://mocharoll.cloud'
EnvBackendUrl = 'https://api.mocharoll.cloud'