[deploy]
bucket = 'cfn-artifacts-mocharoll'
region = 'us-west-2'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'sblasa/aws-bootcamp-cruddur-2023'
BuildSpec = 'backend-flask/buildspec.yml'
ArtifactBucketName = "codepipeline-mocharoll-artifacts"