[deploy]
bucket = 'cfn-artifacts-mocharoll'
region = 'us-west-2'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-west-2:542558699829:certificate/641db304-4fd4-41f8-baf4-a68ebb70949f'
WwwBucketName = 'www.mocharoll.cloud'
RootBucketName = 'mocharoll.cloud'
HostedZoneId = 'Z08803681DMUOOMUA61TQ'